# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de107b1828ccc46326d8470f9ddb578edba3cec2ea85cef176ad610ad968150ff9b01e8849028aafaff1d66079908a978abd7d8f2665fda30e9f5ca65abcbcbb

test:
  secret_key_base: 3860418a80c20949e9b061445cc02660ce46206f232c9e3add964b04752faefc17f06bd00f074c460f82c24b42ecd0e24540d58f8a1f44ce45784878a23edf2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
